name: 🧪 Test

on:
  push:
    branches:
      - main
    paths:
      - "**.ts"
      - deno.lock
      - .github/workflows/test.yml
  pull_request:
    paths:
      - "**.ts"
      - deno.lock
      - .github/workflows/test.yml

jobs:
  Deno:
    runs-on: Ubuntu-Latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@916edb9a40fd86d1ff57b758807ebe57242f7407 # v1.4.0
        with:
          deno-version: v1.x

      - name: 🧪 Run Tests
        run: deno task test

      - name: 🧹 Lint Check
        run: deno lint

      - name: 📚 Lint the JSDoc
        run: deno doc --lint ./src

      - name: 📝 Format Check
        run: deno fmt --check

      - name: 🔍 Type Check
        run: deno check ./src
